Update run_autotests.yml

diff --git a/.github/workflows/run_autotests.yml b/.github/workflows/run_autotests.yml
--- a/.github/workflows/run_autotests.yml
+++ b/.github/workflows/run_autotests.yml
@@ -27,24 +27,38 @@ jobs:
       - name: Set up Python 
         uses: actions/setup-python@v5
         with:
-          python-version: "3.10"   
-      - run: >
-          ARTIFACT_ID=$(curl -L 
-          -H "Accept: application/vnd.github+json" 
-          -H "X-GitHub-Api-Version: 2022-11-28" 
-          "https://api.github.com/repos/alliskov/magento-UI_test_automation/actions/artifacts?name=allure-results" 
-          | python3 -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);")
-          &&
-          curl -L 
-          -H "Accept: application/vnd.github+json" 
-          -H "Authorization: Bearer ${{ secrets.token }}" 
-          -H "X-GitHub-Api-Version: 2022-11-28" 
-          https://api.github.com/repos/alliskov/magento-UI_test_automation/actions/artifacts/$ARTIFACT_ID/zip 
-          -o artifact.zip                
-      - run: mkdir allure-results && unzip artifact.zip -d allure-results
-      - run: mkdir previous_pages && unzip previous_pages.zip -d pages && tar -xvf previous_pages/artifact.tar -c pages_history
-      - run: cp pages_history/history/* allure-results && cp pages_history/history allure-results
-      
+          python-version: "3.10" 
+          
+      - name: Fetch artifact ID
+        id: fetch-artifact
+        run: |
+          response=$(curl -L \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            "https://api.github.com/repos/alliskov/magento-UI_test_automation/actions/artifacts?name=allure-results")
+          
+          artifact_id=$(echo "$response" | jq -r '.artifacts[0].id // empty')
+          if [ -z "$artifact_id" ]; then
+            echo "Artifact not found or empty response."
+            exit 1
+          fi
+
+          echo "artifact_id=$artifact_id" >> $GITHUB_ENV
+
+      - name: Download artifact
+        run: |
+          curl -L \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.token }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            "https://api.github.com/repos/alliskov/magento-UI_test_automation/actions/artifacts/$artifact_id/zip" \
+            -o artifact.zip
+
+      - name: Extract artifact
+        run: |
+          mkdir allure-results
+          unzip artifact.zip -d allure-results
+
       - name: Save reports history
         uses: actions/upload-artifact@v4
         with:
