Update run_autotests.yml

diff --git a/.github/workflows/run_autotests.yml b/.github/workflows/run_autotests.yml
--- a/.github/workflows/run_autotests.yml
+++ b/.github/workflows/run_autotests.yml
@@ -32,8 +32,7 @@ jobs:
       - name: Install dependencies
         run: sudo apt-get update && sudo apt-get install -y unzip jq
 
-      - name: Fetch artifact ID
-        id: fetch-artifact
+      - name: Fetch artifact ID        
         run: |
           response=$(curl -L \
             -H "Accept: application/vnd.github+json" \
@@ -61,6 +60,39 @@ jobs:
         run: |
           mkdir allure-results
           unzip artifact.zip -d allure-results
+                
+      - name: Fetch report ID        
+        run: |
+          response=$(curl -L \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            "https://api.github.com/repos/alliskov/magento-UI_test_automation/actions/artifacts?name=github-pages")
+          
+          report_id=$(echo "$response" | jq -r '.artifacts[0].id // empty')
+          if [ -z "$report_id" ]; then
+            echo "Report ID not found or empty response."
+            exit 1
+          fi
+
+          echo "report_id=$report_id" >> $GITHUB_ENV
+
+      - name: Download report history
+        run: |
+          curl -L \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.token }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            "https://api.github.com/repos/alliskov/magento-UI_test_automation/actions/artifacts/$report_id/zip" \
+            -o report.zip
+
+      - name: Extract report history
+        run: |
+          mkdir report
+          unzip report.zip -d report
+          tar -xvf report/artifact.tar -C report
+          ls -la report/history
+          cp -r report/history/ allure-results
+          ls -la allure-results/history      
 
       - name: Save reports history
         uses: actions/upload-artifact@v4
