Update run_autotests.yml

diff --git a/.github/workflows/run_autotests.yml b/.github/workflows/run_autotests.yml
--- a/.github/workflows/run_autotests.yml
+++ b/.github/workflows/run_autotests.yml
@@ -23,46 +23,35 @@ jobs:
   get-history:
     runs-on: ubuntu-latest
     name: Get report history
-    steps:
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: "3.10"
-
+    steps: 
       - name: Install dependencies
         run: sudo apt-get update && sudo apt-get install -y unzip jq
 
-      - name: Fetch artifact ID        
+      - name: Get previous allure-results        
         run: |
           response=$(curl -L \
             -H "Accept: application/vnd.github+json" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             "https://api.github.com/repos/alliskov/magento-UI_test_automation/actions/artifacts?name=allure-results")
-          
+            
           artifact_id=$(echo "$response" | jq -r '.artifacts[0].id // empty')
-          if [ -z "$artifact_id" ]; then
-            echo "Artifact not found or empty response."
-            exit 1
+          if [ -n "$artifact_id" ]; then
+            run: |
+              curl -L \
+                -H "Accept: application/vnd.github+json" \
+                -H "Authorization: Bearer ${{ secrets.token }}" \
+                -H "X-GitHub-Api-Version: 2022-11-28" \
+                "https://api.github.com/repos/alliskov/magento-UI_test_automation/actions/artifacts/$artifact_id/zip" \
+                -o artifact.zip
+                mkdir allure-results
+                unzip artifact.zip -d allure-results
+                rm -r allure-results/history
+            echo "artifact_id=$artifact_id" >> $GITHUB_ENV            
           fi
+            echo "Results not found or empty response."
+            exit 1
 
-          echo "artifact_id=$artifact_id" >> $GITHUB_ENV
-
-      - name: Download artifact
-        run: |
-          curl -L \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer ${{ secrets.token }}" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            "https://api.github.com/repos/alliskov/magento-UI_test_automation/actions/artifacts/$artifact_id/zip" \
-            -o artifact.zip
-
-      - name: Extract artifact
-        run: |
-          mkdir allure-results
-          unzip artifact.zip -d allure-results
-          rm -r allure-results/history
-                
-      - name: Fetch report ID        
+      - name: Put report history into results
         run: |
           response=$(curl -L \
             -H "Accept: application/vnd.github+json" \
@@ -70,34 +59,24 @@ jobs:
             "https://api.github.com/repos/alliskov/magento-UI_test_automation/actions/artifacts?name=github-pages")
           
           report_id=$(echo "$response" | jq -r '.artifacts[0].id // empty')
-          if [ -z "$report_id" ]; then
-            echo "Report ID not found or empty response."
-            exit 1
+          if [ -n "$report_id" ]; then
+            run: |
+              curl -L \
+                -H "Accept: application/vnd.github+json" \
+                -H "Authorization: Bearer ${{ secrets.token }}" \
+                -H "X-GitHub-Api-Version: 2022-11-28" \
+                "https://api.github.com/repos/alliskov/magento-UI_test_automation/actions/artifacts/$report_id/zip" \
+                -o report.zip
+                mkdir report
+                unzip report.zip -d report
+                tar -xvf report/artifact.tar -C report
+                cp -r report/history/ allure-results
+            echo "report_id=$report_id" >> $GITHUB_ENV
           fi
-
-          echo "report_id=$report_id" >> $GITHUB_ENV
-
-      - name: Download report history
-        run: |
-          curl -L \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer ${{ secrets.token }}" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            "https://api.github.com/repos/alliskov/magento-UI_test_automation/actions/artifacts/$report_id/zip" \
-            -o report.zip
-
-      - name: Extract report history
-        run: |
-          mkdir report
-          unzip report.zip -d report
-          tar -xvf report/artifact.tar -C report
-          cp -r report/history/ allure-results          
-          echo "LS REPORT/HISTORY"
-          ls -la report/history
-          echo "LS ALLURE-RESULTS/HISTORY"
-          ls -la allure-results/history
+            echo "Report not found or empty response."
+            exit 1       
           
-      - name: Save reports history
+      - name: Save updated allure-results
         uses: actions/upload-artifact@v4
         with:
           name: allure-results
