Update run_autotests.yml

diff --git a/.github/workflows/run_autotests.yml b/.github/workflows/run_autotests.yml
--- a/.github/workflows/run_autotests.yml
+++ b/.github/workflows/run_autotests.yml
@@ -35,23 +35,30 @@ jobs:
       - name: Fetch artifact ID
         id: fetch-artifact
         run: |
-          response=$(curl -L \
+          response=$(curl -L -w "%{http_code}" -o response.json \
             -H "Accept: application/vnd.github+json" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             "https://api.github.com/repos/alliskov/magento-UI_test_automation/actions/artifacts?name=allure-results")
           
-          echo "Response from API: $response"
+          http_code=$(tail -n1 <<< "$response")
+          if [ "$http_code" -ne 200 ]; then
+            echo "Error fetching artifacts. HTTP code: $http_code"
+            cat response.json
+            exit 1
+          fi
           
-          artifact_id=$(echo "$response" | jq -r '.artifacts[0].id // empty')
+          artifact_id=$(cat response.json | jq -r '.artifacts[0].id // empty')
           if [ -z "$artifact_id" ]; then
-            echo "Artifact not found or empty response."
+            echo "Artifact not found in the API response."
+            cat response.json
             exit 1
           fi
       
           echo "artifact_id=$artifact_id" >> $GITHUB_ENV
+          
       - name: Download artifact
         run: |
-          curl -L \
+          curl -L -v \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ secrets.token }}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
