Update run_autotests.yml

diff --git a/.github/workflows/run_autotests.yml b/.github/workflows/run_autotests.yml
--- a/.github/workflows/run_autotests.yml
+++ b/.github/workflows/run_autotests.yml
@@ -21,27 +21,47 @@ on:
 
 jobs:
   get-history:
-    runs-on: ubuntu_latest
+    runs-on: ubuntu-latest
     name: Get report history
     steps:
-      - name: Set up Python 
+      - name: Set up Python
         uses: actions/setup-python@v5
         with:
-          python-version: "3.10"   
-      - run: >
-          ARTIFACT_ID=$(curl -L 
-          -H "Accept: application/vnd.github+json" 
-          -H "X-GitHub-Api-Version: 2022-11-28" 
-          "https://api.github.com/repos/alliskov/magento-UI_test_automation/actions/artifacts?name=allure-results" 
-          | python3 -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);")
-          &&
-          curl -L 
-          -H "Accept: application/vnd.github+json" 
-          -H "Authorization: Bearer ${{ secrets.token }}" 
-          -H "X-GitHub-Api-Version: 2022-11-28" 
-          https://api.github.com/repos/alliskov/magento-UI_test_automation/actions/artifacts/$ARTIFACT_ID/zip 
-          -o artifact.zip   
-      - run: mkdir allure-results && unzip artifact.zip -d allure-results
+          python-version: "3.10"
+
+      - name: Install dependencies
+        run: sudo apt-get update && sudo apt-get install -y unzip jq
+
+      - name: Fetch artifact ID
+        id: fetch-artifact
+        run: |
+          response=$(curl -L \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            "https://api.github.com/repos/alliskov/magento-UI_test_automation/actions/artifacts?name=allure-results")
+          
+          artifact_id=$(echo "$response" | jq -r '.artifacts[0].id // empty')
+          if [ -z "$artifact_id" ]; then
+            echo "Artifact not found or empty response."
+            exit 1
+          fi
+
+          echo "artifact_id=$artifact_id" >> $GITHUB_ENV
+
+      - name: Download artifact
+        run: |
+          curl -L \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.token }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            "https://api.github.com/repos/alliskov/magento-UI_test_automation/actions/artifacts/$artifact_id/zip" \
+            -o artifact.zip
+
+      - name: Extract artifact
+        run: |
+          mkdir allure-results
+          unzip artifact.zip -d allure-results
+          
       - name: Save reports history
         uses: actions/upload-artifact@v4
         with:
@@ -57,39 +77,50 @@ jobs:
     steps:       
       - name: Check out source repository
         uses: actions/checkout@v4
+        
       - name: Set up Python 
         uses: actions/setup-python@v5
         with:
           python-version: "3.10"
+          
       - name: Set up test environment
         run: pip install -r requirements.txt
+        
       - name: Download workflow artifacts
         uses: actions/download-artifact@v4
+        
       - name: Run all tests
         if: "github.event.inputs.deployment_target == 'all'"
         run: pytest --alluredir=allure-results
         continue-on-error: true
+        
       - name: Run extended test set
         if: "github.event.inputs.deployment_target == 'extended'"
         run: pytest -m extended --alluredir=allure-results
         continue-on-error: true
+        
       - name: Run regression test set
         if: "github.event.inputs.deployment_target == 'regression'"
         run: pytest -m regression --alluredir=allure-results
         continue-on-error: true
+        
       - name: Run smoke test set
         if: "github.event.inputs.deployment_target == 'smoke'"
         run: pytest -m smoke --alluredir=allure-results
         continue-on-error: true
+        
       - name: Install Java      
         uses: actions/setup-java@v4
         with:
           distribution: "microsoft"
           java-version: "17"
+          
       - name: Install Allure
         run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.32.0/allure-2.32.0.tgz && sudo tar -zxvf allure-2.32.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.32.0/bin/allure /usr/bin/allure
+        
       - name: Generate report
         run: allure generate -c allure-results -o allure-report
+      
       - name: Save report
         uses: actions/upload-artifact@v4
         with:
@@ -104,10 +135,12 @@ jobs:
     steps: 
       - name: Download artifacts
         uses: actions/download-artifact@v4
+      
       - name: Upload Pages artifact
         uses: actions/upload-pages-artifact@v3
         with:
           path: allure-report/
+      
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v4
